# The secrets.VAR_NAME values are defined in the
# github repo's Settings -> Secrets area.
name: Deploy
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["ruby-ci"]
    types: [completed]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
      - name: Run Migrations
        run: heroku run bin/rails db:migrate
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Skipped deployment. Test failure.')
